anwesenheit/urls.py
from django.urls import path


from .views import start, anw_group, anw_detail, savedate, anw_note, anw_raum, saveplan, delplan, savedateplan

app_name = "anw"
    
urlpatterns = [
    path('', start ,name='start'),
    path('<int:id>', anw_group ,name='anw_g'),
    path('detail/<int:id>', anw_detail ,name='anw_detail'),
    path('detail/<int:id>/<str:aim_date>', anw_detail ,name='savedate_date'), 
    path('raum/<int:group>/<str:date>', anw_raum ,name='anw_raum'), 
    path('detail_tnnote/', anw_note, name='anw_note'), 
    path('savedate', savedate, name='savedate'),
    path('savedateplan', savedateplan, name='savedateplan'),

    path('saveplan', saveplan, name='saveplan'),
    path('delplan', delplan, name='delplan'),
]

mausb/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('stammdaten/',include('stammdaten.urls')),
    path('anw/', include('anwesenheit.urls')),
    path('plan/', include('ausbildungsplan.urls')),
    path('admin/', admin.site.urls, name="admin"),
    path('', include('start.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

anwesenheit/models.py
from django.db import models
from django.urls import reverse

from stammdaten.models import Ausbilder, Teilnehmer, Raum


# Create your models here.

class TNAnwesend(models.Model):
    teilnehmer = models.ForeignKey(Teilnehmer, verbose_name="Teilnehmer", on_delete=models.CASCADE)
    ausbilder = models.ForeignKey(Ausbilder, verbose_name="Ausbilder", on_delete=models.CASCADE)
    datum = models.DateTimeField("Datum", auto_now=False, auto_now_add=True)
    anwesend = models.BooleanField("Anwesend")
    comment = models.TextField(("Kommentar"), null=True, blank=True)

    class Meta:
        verbose_name = "Teilnehmer Anwesenheit"
        verbose_name_plural = "Teilnehmer Anwesenheiten"
        ordering = ['teilnehmer', '-datum']

    def __str__(self):
        return f"{self.teilnehmer} {self.anwesend}/{self.datum}"

    def get_absolute_url(self):
        return reverse("TNAnwesend_detail", kwargs={"pk": self.pk})

class Sitzplan(models.Model):
    raum =  models.ForeignKey(Raum, verbose_name=("Raum"), on_delete=models.CASCADE)
    teilnehmer = models.ForeignKey(Teilnehmer, verbose_name=("Teilnehmer"), on_delete=models.CASCADE, null=True)
    col = models.IntegerField(("Spalte"))
    row = models.IntegerField(("Reihe"))
 
    class Meta:
        verbose_name = ("Sitzplan")
        verbose_name_plural = ("Sitzpläne")

    def __str__(self):
        return f"{self.raum} ({self.row}/{self.col} {self.teilnehmer})"

    def get_absolute_url(self):
        return reverse("Sitzplan_detail", kwargs={"pk": self.pk})

anwesenheit/views.py
import datetime
import json
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404, render
from django.contrib.auth.models import User

from stammdaten.models import Team, Gruppe, Teilnehmer, Ausbilder, TNAnmerkung, Raum
from .models import TNAnwesend, Sitzplan

import stammdaten.classForm as cform

from django.contrib.auth.decorators import permission_required

# from datetime import date, datetime
from django.utils.timezone import activate

# Create your views here.

def start(request):
    # Erstaufruf zur Auswahl des Teams
    teams = Team.objects.filter(activ = True)
    # Nur ein Team?
    if len(teams)==1 :
        return redirect(f"/anw/{teams[0].id}")
    
    teams = cform.FormAuswahl("Teams", Team, leerzeile=True, aktiv=True, onclick='anw_group(this.value)')
    
   #
    content = {
        'cont': 'anw:start',            # Zurück bei Anmeldung
        'teams': teams,                 # Alle aktiven Teams
    }
    return render(request,"anwesenheit/anw_team.html", content)

@permission_required('stammdaten.view_gruppe', raise_exception=True)
def anw_group(request, id):
    # Auswahl der Gruppe
    team = get_object_or_404(Team, id=id)
    teams = cform.FormAuswahl("Teams", Team, leerzeile=True, aktiv=True, value=team.id,  onclick='anw_group(this.value)')
    groups = Gruppe.objects.filter(activ=True, team=team)
    select_groups = cform.FormAuswahl("Gruppe", daten=groups, leerzeile=True, onclick='anw_detail(this.value)')
    content = {
        'cont': 'anw:anw_g/1',
        'team': team,
        'teams': teams,
        'groups': select_groups,
    }
    return render(request,"anwesenheit/anw_group.html", content)


@permission_required('anwesenheit.add_tnanwesend', raise_exception=True)
def anw_detail(request, id, aim_date=None):
    # aim_date != today --> Auswertung, Änderungen werden blockiert
    if aim_date == None:
        datum = datetime.date.today()
        passiv = False
    else:
        passiv = True
        datum = datetime.datetime.strptime(aim_date, "%Y-%m-%d").date()
        if datum == datetime.date.today():    # --> doch aktueller Tag, Änderungen möglich
            passiv = False

    gruppe = get_object_or_404(Gruppe, id=id)
    team = gruppe.team
    groups = Gruppe.objects.filter(activ=True, team=team)

    teams = cform.FormAuswahl("Teams", Team, leerzeile=True, aktiv=True, value=team.id,  onclick='anw_group(this.value)')
    select_groups = cform.FormAuswahl("Gruppe", daten=groups, leerzeile=True, value=id, onclick='anw_detail(this.value)')

    tn_group = Teilnehmer.objects.filter(activ=True, group=gruppe)
    tn_count = len(tn_group)
    tn_count_anw = 0
    elements = []
    for tn in tn_group:
        ds = TNAnwesend.objects.filter(teilnehmer=tn, datum__date = datum)
        ds_notes = TNAnmerkung.objects.filter(teilnehmer=tn, date__date = datum)

        if len(ds)>0:
            anwesend = ds[0].anwesend
            code = 1 if anwesend else 2
            tn_count_anw += 1 if anwesend else 0                    # Anzahl der Anwesenden hochzählen
            str_anw = ""
            for termin in ds:
                color = "text-success" if termin.anwesend else "text-danger"
                icon = "hand-thumbs-up-fill" if termin.anwesend else "ban-fill"
                time = termin.datum.strftime("%H:%M")
                str_anw += f'<span title="'+termin.ausbilder.short+'"><i class="bi bi-'+ icon +' me-2 ' + color +'"></i>' + time +';</span> '
        else:
            code = 0
            str_anw = ""
        if len(ds_notes) > 0:       # Notizen vorhanden
            str_anw += '<span title="'
            for ds_note in ds_notes:
                str_anw += f"{ds_note.ausbilder.short} {ds_note.date.strftime("%H:%M")} - {ds_note.comment}\n"
            str_anw += '"><i class="bi bi-envelope me-2"></i>;</span>'


        elements.append((tn, code, ds, str_anw))

    content = {
        'cont': 'anw:start',
        'teams': teams,
        'groups': select_groups,
        'teilnehmer': elements,
        'aim_date': datum.strftime("%Y-%m-%d"),
        'gruppe': gruppe,
        'passiv': passiv,
        'count_tn': tn_count,
        'count_tn_anw': tn_count_anw
        
    }
    return render(request,"anwesenheit/anw_detail.html", content)

# Daten aus Formular speichern
@permission_required('anwesenheit.add_tnanwesend', raise_exception=True)
def savedate(request):
    if request.method == 'POST':
        teilnehmer = request.POST['teilnehmer']
        anwesend = request.POST['anwesend']
        anwesend = True if anwesend=="true" else False
        ds_ausbilder = get_object_or_404(Ausbilder, user=request.user)
        ds_teilnehmer = get_object_or_404(Teilnehmer, id=teilnehmer)
        ds_termin = TNAnwesend(teilnehmer=ds_teilnehmer, anwesend=anwesend, ausbilder = ds_ausbilder)
        ds_termin.save()
        answer = {
            'error': False,
            'time': ds_termin.datum.strftime("%H:%M"),
            'ausbilder': ds_termin.ausbilder.short,
        }
        return HttpResponse(json.dumps(answer), content_type="application/json")
    else:
        answer = {
            'error': True,
        }
        return HttpResponse(json.dumps(answer), content_type="application/json")

# Notiz über Teilnehmer    
@permission_required('stammdaten.add_tnanmerkung', raise_exception=True)
def anw_note(request):
    ds_tn = get_object_or_404(Teilnehmer, id=request.POST['tn'])
    ds_ausbilder = get_object_or_404(Ausbilder, user=request.user)
    ds  = TNAnmerkung(teilnehmer=ds_tn, ausbilder= ds_ausbilder, comment = request.POST['note'])
    ds.save()
    answer = {
        'error': False,
        'ausbilder': ds.ausbilder.short,
        'note': ds.comment,
        'time': ds.date.strftime('%d.%m.%Y %H:%M'),
    }
    return HttpResponse(json.dumps(answer), content_type="application/json")

@permission_required('anwesenheit.view_sitzplan', raise_exception=True)
def anw_raum(request, group, date):
    group = get_object_or_404(Gruppe, id = group)
    raum = group.raum
    lst_tn = Teilnehmer.objects.filter(group=group, activ=True)
    lst_teilnehmer= []
    for tn in lst_tn:
        if len(Sitzplan.objects.filter(raum = raum, teilnehmer = tn)) == 0:
            lst_teilnehmer.append(tn)

    elements = []
    if raum:
        for reihe in range(raum.row):
            lst_reihe = []
            for spalte in range(raum.col):
                plan =  Sitzplan.objects.filter(row=reihe, col=spalte, raum=raum)
                if len(plan)>0: #Teilnehmer am Platz vorhanden
                    # Anwesenheit aktueller Tag prüfen
                    akt_datum = datetime.date.today()
                    anw_ds = TNAnwesend.objects.filter(teilnehmer = plan[0].teilnehmer, datum__date = akt_datum)
                    if len(anw_ds) == 0 :         # kein Datensatz --> keine aktuelle Buchung
                        bg_color_code = "bg-secondary bg-gradient"
                    else:                       # DS vorhanden, nach Datum sortiert, der letzte gilt
                        bg_color_code = "bg-success bg-gradient" if anw_ds[0].anwesend else "bg-danger bg-gradient"
                    lst_reihe.append((plan[0], bg_color_code))
                else:
                    lst_reihe.append(None)   
            elements.append(lst_reihe)  
    content = {
        'gruppe': group,
        'raum': raum,
        'elements': elements,
        'teilnehmer': lst_teilnehmer,
    }
    return render(request, "anwesenheit/anw_plan.html", content)

@permission_required('anwesenheit.change_sitzplan', raise_exception=True)
# Sitzplatz speichern D&D
def saveplan(request):
    raum = request.POST['raum']
    teilnehmer = request.POST['teilnehmer']
    spalte = request.POST['spalte']
    zeile = request.POST['zeile']
    ds_raum = get_object_or_404(Raum, id=raum)
    ds_teilnehmer = get_object_or_404(Teilnehmer, id=teilnehmer)
  
    ds_sitz, create = Sitzplan.objects.get_or_create(raum=ds_raum, row = zeile, col = spalte)

    ds_tn_alt = ds_sitz.teilnehmer
    ds_sitz.teilnehmer = ds_teilnehmer
    ds_sitz.save()

    # Anwesenheitsfarbe ermitteln
    ds_tn_anw = TNAnwesend.objects.filter(teilnehmer=ds_teilnehmer, datum__date = datetime.date.today())
    if len(ds_tn_anw) == 0:
        bg_color = "bg-secondary"
    else:
        bg_color = "bg-success" if ds_tn_anw[0].anwesend else "bg-danger"

    answer = {
        'error': False,
        'teilnehmer': ds_teilnehmer.__str__(),
        'teilnehmer_id': ds_teilnehmer.id,
        'teilnehmer_old': ds_tn_alt.__str__(),
        'tno_id': ds_tn_alt.id if ds_tn_alt else None,
        'tn_picture': ds_sitz.teilnehmer.picture.url,
        'bg_color': bg_color,
        'plan_id': ds_sitz.id, 
    }
    return HttpResponse(json.dumps(answer), content_type="application/json")

@permission_required('anwesenheit.delete_sitzplan', raise_exception=True)
def delplan(request):
    ds = get_object_or_404(Sitzplan, id=int(request.POST['id']))
    ds_teilnehmer = ds.teilnehmer
    zeile = ds.row
    spalte = ds.col
    ds.delete()
    answer = {
        'zeile': zeile,
        'spalte': spalte,
        'error': False,
        'teilnehmer_id': ds_teilnehmer.id,
        'teilnehmer': ds_teilnehmer.__str__(),
        'tn_picture': ds_teilnehmer.picture.url,
    }
    return HttpResponse(json.dumps(answer), content_type="application/json")

# Anwesenheit aus Sitzplan speichern
@permission_required('anwesenheit.add_tnanwesend', raise_exception=True)
def savedateplan(request):
    ds_tn = get_object_or_404(Teilnehmer, id=request.POST['teilnehmer'])

    # Aktuelle Anwesenheit?
    ds_tn_anw = TNAnwesend.objects.filter(teilnehmer=ds_tn, datum__date = datetime.date.today())
    if len(ds_tn_anw)==0 :              # Noch keine Eintragung erstmal abwesend
        anwesenheit = False
    else:                               # ansonsten Gegenteil der letzten Eintragung
        anwesenheit = not ds_tn_anw[0].anwesend
    # Ausbilder ermitteln

anwesenheit/templates/anwesenheit/anw_basis.html
{% extends "stammdaten/base.html" %}

{% block title %}Anwesenheit{% endblock title %}

anwesenheit/templates/anwesenheit/anw_detail.html
{% extends "anwesenheit/anw_group.html" %}

{% block content %}
<style>

</style>
    <script>
        function generate_btn(teilnehmer, anwesend) {
            let btn_color = anwesend ? "success" : "danger";
            let btn_text = anwesend ? "Anwesend" : "Abwesend";
            let btn_code = anwesend ? 2 : 1;
            let str_btn =   "<div class='col-3'>";
            str_btn +=          `<button type="button" class="btn-block btn btn-outline-${btn_color}" onclick="addtermin(${teilnehmer}, ${btn_code}, false)">${btn_text}</button>`;
            str_btn +=      "</div>";
            $('#btn'+ teilnehmer).html(str_btn);
        }
    </script>
    <div class="row"> 
        {% comment %} Überschrift mit Gruppenzähler {% endcomment %}
        <div class="col text-center">
            <h2>{{gruppe}}  <span id="count_anw" >{{count_tn_anw}}</span>/{{count_tn}} </h2>
        </div>
        {% comment %} Button Raum {% endcomment %}
        <div class="col">
            <a href="{% url 'anw:anw_raum' group=gruppe.id date=aim_date %}"><button type="button" class="btn btn-outline-dark float-end">Raum</button></a>
        </div>
    </div>
    {% comment %} Liste Teilnehmer {% endcomment %}
    {% for tn in teilnehmer %}
         {% comment %} Keine Einträge für den Tag {% endcomment %}
        <div class="row m-2 border border-2 rounded-pill row border-dark shadow bg-light bg-opacity-75">
            {% comment %} Name und eventuell Bild Teilnehmer {% endcomment %}
            <div class = "col-4 fs-4">
                <a href="/admin/stammdaten/teilnehmer/{{tn.0.id}}/change/" target="__blank"><i class="bi bi-sliders text-body-secondary"></i></a>
                <i class="bi bi-info-circle"></i>
                <span class="hover-title" onclick="ontn({{tn.0.id}}, '{{tn.0.name}}', true)">{{tn.0.name}} ({{tn.0.profession.short}})</span>
                {% if tn.0.picture %}<div class="hover-image bg-opacity-100 shadow"><img class="" src="{{ tn.0.picture.url }}"/></div>{% endif %}
            </div>
            {% comment %} Button Anwesenheit {% endcomment %}
            <div class="col-3 row {% if passiv %}d-none{% endif %}" id="btn{{tn.0.id}}">
                <div class = "col">
                    <button type="button" class="btn btn-outline-success"  onclick="addtermin({{tn.0.id}}, 1, true)">Anwesend</button>
                </div>
                <div class = "col">
                    <button type="button" class="btn btn-outline-danger" onclick="addtermin({{tn.0.id}}, 2, true)">Abwesend</button>
                </div>
            </div>
            <div class="col">
                <p id="fz{{tn.0.id}}">{{tn.3 | safe}}</p>
            </div> 
        </div>
        <script>
            {% if tn.1 != 0 %}
                generate_btn({{tn.0.id}}, '{{tn.2.0.anwesend}}' == 'True' ? true : false);
            {% endif %}
        </script>    
    {% endfor %}

    <script>
        function ontn(tn_id, tn_name) {
            antwort = prompt(`Anmerkung zu TN: ${tn_name}: `);
            // Abbruch --> antwort = null
            if (antwort != null) {
                $.ajax({
                    type: "POST",
                    url: "{% url 'anw:anw_note' %}",
                    data: {
                        tn: tn_id,
                        note: antwort,
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    },
                    success: function(data) {
                        let answer_str=$('#fz'+tn_id).html()+`<span title="${data['ausbilder']} ${data['time']} - ${data['note']}"><i class="bi bi-envelope me-2"></i>;</span> `;
                        $('#fz'+tn_id).html(answer_str);
                    }
                });
            }
        }
        function addtermin(teilnehmer, code, newtermin) {
            anwesend = code == 1 ? true : false;
            $.ajax({
                type: "POST",
                url: "{% url 'anw:savedate' %}",
                data: {
                    teilnehmer: teilnehmer,
                    anwesend: anwesend,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(data) {
                    // Button neu generieren
                    generate_btn(teilnehmer, anwesend);
                    // Zähler Überschrift hochzählen
                    let counter = parseInt($('#count_anw').text());
                    if (anwesend) {
                        counter++;
                    } else {
                        if (!newtermin) {
                            counter--;
                        }
                    }
                    $('#count_anw').text(counter);
                    // Anwesenheitsliste generieren
                    
                    time = data['time']
                    let color = ""
                    if (code == '1') {
                        color = "text-success"
                    }
                    else {
                        color = "text-danger"
                    }
                    let icon = code == '1' ? "hand-thumbs-up-fill" : "ban-fill";   
                    let string = '<span title="'+data['ausbilder']+'"><i class="bi bi-'+ icon +' me-2 ' + color +'"></i>' + time +';</span> '+$('#fz'+teilnehmer).html()
                    $('#fz'+teilnehmer).html(string);
                }
            });
        }
    </script>
{% endblock content %}

anwesenheit/templates/anwesenheit/anw_group.html
{% extends "anwesenheit/anw_basis.html" %}

{% block zusatzmenue %}
    <div class="col mb-2">
        {{ teams | safe }}
    </div>
    <div class="col mb-2">
        {{ groups | safe }}
    </div>
    <div class="col mb-2">
        <label for"date">Datum<label>
        <input type="date" id="date" class="form-control" value="{{aim_date}}" onchange="set_date({{gruppe.id}}, this.value)">
    </div>

{% endblock zusatzmenue %}

{% block js %}
    <script> 
        function set_date(gruppe, aim_date) {
            aim = "{% url 'anw:savedate_date' id=1234 aim_date='5678' %}".replace('1234', gruppe).replace('5678', aim_date);
            window.location.replace(aim);
        }
        function anw_group(id) {
            if (id == "---") {
                window.location.replace("{% url 'anw:start' %}"); 

            } else {
                aim = "{% url 'anw:anw_g' id=123 %}".replace('123', id);
                window.location.replace(aim);
            }
        }
    </script>

    <script>
        function anw_detail(id) {
            if (id != "---") {
                aim = "{% url 'anw:anw_detail' id=123 %}".replace('123', id);
                window.location.replace(aim);
            }
        }
    </script>

    
{% endblock js %}

anwesenheit/templates/anwesenheit/anw_plan.html
{% extends "stammdaten/base.html" %}

{% block title %}Sitzplan{% endblock title %}

{% block content_fluid %}
<div class="row">
    {% comment %} Sitzplan {% endcomment %}
    <div class="col-9 row">
        <div class="col">
            <h1>Sitzplan Raum {{raum.bezeichnung}}</h1>
        </div>
        {% comment %} Button Raum {% endcomment %}
        <div class="col">
            <a href="{% url 'anw:anw_detail' id=gruppe.id %}"><button type="button" class="btn btn-outline-dark float-end">Anwesenheit</button></a>
        </div>
        {% for reihe in elements %}
            <div class="row border">
            {% for spalte in reihe %}
                {% comment %} Reihe für Gang freilassen {% endcomment %}
                {% if raum.gang == forloop.counter %} 
                    <div class="col shadow rounded-pill "></div>
                {% endif %}
                {% comment %} Sitzplatz für Sitzplatz {% endcomment %}
                <div id="sitz{{forloop.parentloop.counter0}}_{{forloop.counter0}}" class="{{spalte.1}} col border shadow m-3 text-center rounded-pill bg-opacity-75"
                 ondrop="dropHandler(event, {{forloop.counter0}}, {{forloop.parentloop.counter0}}, {{raum.id}})" ondragover="dragoverHandler(event)">
                    {% if spalte %}
                        <span class="hover-title" onclick="onclick_plan({{spalte.0.teilnehmer.id}})">
                            {{spalte.0.teilnehmer}} 
                        </span>
                        {% if spalte.0.teilnehmer.picture %}
                        <div class="hover-image bg-opacity-100 shadow">
                            <img src="{{ spalte.0.teilnehmer.picture.url }}"/>
                        </div>{% endif %}
                        <i class="bi bi-trash" onclick="del_sitz({{spalte.0.id}})"></i>                       
                    {% else %}
                         - 
                    {% endif %}
                </div>
            {% endfor %}    
            </div>   
        {% endfor %}
    </div>

    {% comment %} Leiste Teilnehmer {% endcomment %}
    <div class="col-2" id="liste_tn">
        {% for tn in teilnehmer %}
            <div id="{{tn.id}}" class="border col-12 m-2 shadow hover-title" draggable="true" ondragstart="dragstartHandler(event)">{{tn}}</div>
            {% if tn.picture %}<div class="hover-image bg-opacity-100 shadow"><img src="{{ tn.picture.url }}"/></div>{% endif %}
        {% endfor %}
    </div>
</div>
<script>
function dragstartHandler(ev) {
  ev.dataTransfer.setData("teilnehmer", ev.target.id);
}

function dragoverHandler(ev) {
  ev.preventDefault();
}

// D&D auf TN auf Sitzplatz
function dropHandler(ev, spalte, zeile, raum) {
    ev.preventDefault();
    const teilnehmer = ev.dataTransfer.getData("teilnehmer");
    // console.log(teilnehmer, zeile, spalte, raum);
    // Backend Save data
    $.ajax({
        type: "POST",
        url: "{% url 'anw:saveplan' %}",
        data: {
            raum: raum,
            zeile: zeile,
            spalte: spalte,
            teilnehmer: teilnehmer,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        success: function(data) {
            // Change Sitz
            div_string = `<span class="hover-title" onclick="onclick_plan(${data['teilnehmer_id']})">
                           ${data['teilnehmer']} 
                        </span>`
            $('#sitz'+zeile+'_'+spalte).html(div_string);

            // Bild hinzufügen
            image_str = `<div class="hover-image bg-opacity-100 shadow"><img src="${data['tn_picture']}"></div>`;
            $('#sitz'+zeile+'_'+spalte).append(image_str);
            
            // Hintergrundfarben löschen
            $('#sitz'+zeile+'_'+spalte).removeClass('bg-secondary');
            $('#sitz'+zeile+'_'+spalte).removeClass('bg-success');
            $('#sitz'+zeile+'_'+spalte).removeClass('bg-danger');
            
            // Hintergrundfarbe setzen
            $('#sitz'+zeile+'_'+spalte).addClass(data['bg_color']);

            // Papierkorb einfügen
            trash_string = `<i class="bi bi-trash" onclick="del_sitz(${data['plan_id']})"></i>`;
            $('#sitz'+zeile+'_'+spalte).append(trash_string);

            // Remove TN von Liste rechts
            $('#'+teilnehmer).remove();
            if (data['teilnehmer_old'] != 'None'){
                let div_str = '<div id="'+data['tno_id']+'" class="border col m-2 shadow" draggable="true" ondragstart="dragstartHandler(event)">'+data['teilnehmer_old']+'</div>'
                $( "#liste_tn" ).append(div_str);
            }
            
        }
    });
  // Remove TN  

}

function del_sitz(id) {
    $.ajax({
        type: "POST",
        url: "{% url 'anw:delplan' %}",
        data: {
            id: id,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        success: function(data) {
            $('#sitz'+data['zeile']+'_'+data['spalte']).text("-")
            
            // Hintergrundfarben löschen
            $('#sitz'+data['zeile']+'_'+data['spalte']).removeClass('bg-secondary');
            $('#sitz'+data['zeile']+'_'+data['spalte']).removeClass('bg-success');
            $('#sitz'+data['zeile']+'_'+data['spalte']).removeClass('bg-danger');

            // Gelöschter Teilnehmer zur TN-Liste hinzufügen
            str_tn_listeintrag = `<div id="${data['teilnehmer_id']}" class="border col-12 m-2 shadow hover-title" draggable="true" ondragstart="dragstartHandler(event)">${data['teilnehmer']}</div>`;
            $('#liste_tn').append(str_tn_listeintrag);
            // Bild hinzufügen
            image_str = `<div class="hover-image bg-opacity-100 shadow"><img src="${data['tn_picture']}"></div>`;
            $('#liste_tn').append(image_str);


        }
    });
    
}

// Anwesenheit Sitzplan 
function onclick_plan(id_tn) {
    $.ajax({
        type: "POST",
        url: "{% url 'anw:savedateplan' %}",
        data: {
            teilnehmer: id_tn,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        success: function(data) {

            // Alle möglichen Farben löschen
            $('#sitz'+data['zeile']+'_'+data['spalte']).removeClass('bg-secondary');
            $('#sitz'+data['zeile']+'_'+data['spalte']).removeClass('bg-success');
            $('#sitz'+data['zeile']+'_'+data['spalte']).removeClass('bg-danger');

            // Neue Hintergrundfarbe setzen
            $('#sitz'+data['zeile']+'_'+data['spalte']).addClass(data['bg_color']);

        }
    });

}
</script>
{% endblock content_fluid %}

anwesenheit/templates/anwesenheit/anw_team.html
{% extends "anwesenheit/anw_basis.html" %}

{% block zusatzmenue %}
    <form method="POST" class="col">
    {% csrf_token %}
        {{ teams | safe }}
    </form>
{% endblock zusatzmenue %}

{% block js %}
    <script>
        function anw_group(id) {
            if (id == "---") {
                window.location.replace("{% url 'anw:start' %}"); 
            } else {
                aim = "{% url 'anw:anw_g' id=123 %}".replace('123', id);
                window.location.replace(aim);
            }
        }
    </script>
{% endblock js %}