anwesenheit/urls.py
from django.urls import path


from .views import start, anw_group, anw_detail, savedate, anw_note, anw_raum, saveplan, delplan, savedateplan

app_name = "anw"
    
urlpatterns = [
    path('', start ,name='start'),
    path('<int:id>', anw_group ,name='anw_g'),
    path('detail/<int:id>', anw_detail ,name='anw_detail'),
    path('detail/<int:id>/<str:aim_date>', anw_detail ,name='savedate_date'), 
    path('raum/<int:group>/<str:date>', anw_raum ,name='anw_raum'), 
    path('detail_tnnote/', anw_note, name='anw_note'), 
    path('savedate', savedate, name='savedate'),
    path('savedateplan', savedateplan, name='savedateplan'),

    path('saveplan', saveplan, name='saveplan'),
    path('delplan', delplan, name='delplan'),
]

ausbildungsplan/urls.py
from django.urls import path
from . import views

app_name = "ausbildungsplan"

urlpatterns = [
    path('', views.start, name = "start"),                      # Start ohne Paramter
    path('<int:team>', views.start, name = "team"),             # Start mit Team ID
    path('<int:team>/<str:date>', views.start, name = "date"),  # Start mit Team ID und Datum 'dd.mm.yyyy'
]

mausb/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('stammdaten/',include('stammdaten.urls')),
    path('anw/', include('anwesenheit.urls')),
    path('plan/', include('ausbildungsplan.urls')),
    path('admin/', admin.site.urls, name="admin"),
    path('', include('start.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stammdaten/urls.py
from django.urls import path
from .views import start, user_login, user_logout

app_name = "stammdaten"

urlpatterns = [
    path('', start ,name='start'),

    path('login', user_login, name="login"),                                                                                  # Login
    path('logout', user_logout, name="logout"),      
]

stammdaten/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here

class Ausbilder(models.Model):
    user = models.OneToOneField(User, verbose_name=("SystemUser"), on_delete=models.RESTRICT)
    short = models.CharField(("Kürzel"), max_length=10)
    activ = models.BooleanField(("Aktiv"), default=True)
    bg_color = models.CharField(("Hintergrundfarbe"), max_length=50, default="DodgerBlue")
    fg_color = models.CharField("Schriftfarbe", max_length=50, default="white")
    comment = models.TextField(("Kommentar"), blank=True, null=True)

    class Meta:
        verbose_name = "Ausbilder"
        verbose_name_plural = "Ausbilder"

    def __str__(self):
        status = "Aktiv" if self.activ else "Inaktiv"
        return f"{self.user.first_name} {self.user.last_name} ({self.short}/{status})"

    def get_absolute_url(self):
        return reverse("Ausbilder_detail", kwargs={"pk": self.pk})

class Raum(models.Model):
    bezeichnung = models.CharField("Bezeichnung", max_length=10)
    info = models.TextField(("Info"))
    row = models.IntegerField(("Reihen"), default=5)
    col = models.IntegerField(("Spalten"), default=6)
    gang = models.IntegerField(("Gang"), default=3)
    
    class Meta:
        verbose_name = "Raum"
        verbose_name_plural = "Räume"

    def __str__(self):
        return f"{self.bezeichnung} - {self.info}"

    def get_absolute_url(self):
        return reverse("Raum_detail", kwargs={"pk": self.pk})

class Standort(models.Model):
    short = models.CharField(("Kürzel"), max_length=10)
    ort = models.CharField("Ort", max_length=50)
    description = models.TextField(("Beschreibung"), null=True, blank=True)
    activ = models.BooleanField("Aktiv", default=True)
    
    class Meta:
        verbose_name = "Standort"
        verbose_name_plural = "Standorte"

    def __str__(self):
        return f"{self.short} - {self.ort}"

    def get_absolute_url(self):
        return reverse("Standort_detail", kwargs={"pk": self.pk})

class Team(models.Model):
    name = models.CharField(("Bezeichnung"), max_length=50)
    short = models.CharField(("Kürzel"), max_length=10)
    aubi = models.ManyToManyField(Ausbilder, verbose_name=("Ausbilder"))
    standort = models.ForeignKey(Standort, verbose_name=("Standort"), on_delete=models.CASCADE)
    head = models.ForeignKey(Ausbilder, verbose_name=("Teamleiter"), related_name="Teamleiter", on_delete=models.RESTRICT, null=True, blank=True)
    activ = models.BooleanField(("aktiv"), default=True)

    class Meta:
        verbose_name = ("Team")
        verbose_name_plural = ("Teams")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Team_detail", kwargs={"pk": self.pk})

class Beruf(models.Model):
    short = models.CharField(("Kürzel"), max_length=10)
    name = models.CharField(("Bezeichnung"), max_length=50)
    activ = models.BooleanField(("Aktiv"), default=True)

    class Meta:
        verbose_name = "Beruf"
        verbose_name_plural = "Berufe"
        ordering = ["short"]

    def __str__(self):
        return f"{self.name} ({self.short})"

    def get_absolute_url(self):
        return reverse("Beruf_detail", kwargs={"pk": self.pk})


class Gruppe(models.Model):
    name = models.CharField("Name", max_length=50)
    short = models.CharField("Kürzel", max_length=10)
    speaker = models.ForeignKey('Teilnehmer', verbose_name=("Gruppensprecher"), on_delete=models.SET_NULL, null=True, blank=True)
    team = models.ForeignKey(Team, verbose_name="Team", on_delete=models.RESTRICT)
    activ = models.BooleanField(("aktiv"), default=True)
    raum = models.ForeignKey(Raum, verbose_name="Raum", on_delete=models.RESTRICT, null = True, blank = True)

    class Meta:
        verbose_name = "Gruppe"
        verbose_name_plural = "Gruppen"
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Gruppe_detail", kwargs={"pk": self.pk})

class Teilnehmer(models.Model):
    name = models.CharField("Name", max_length=50)
    profession = models.ForeignKey(Beruf, verbose_name=("Beruf"), on_delete=models.RESTRICT)
    group = models.ForeignKey(Gruppe, verbose_name=("Gruppe"), on_delete=models.CASCADE)
    picture = models.ImageField(("Bild"), upload_to="stammdaten/tnimg", height_field=None, width_field=None, max_length=None, null=True, blank=True)
    activ = models.BooleanField(("aktiv"), default=True)

    class Meta:
        verbose_name = "Teilnehmer"
        verbose_name_plural = "Teilnehmer"
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} ({self.profession.short}/{self.group.short})"

    def get_absolute_url(self):
        return reverse("Teilnehmer_detail", kwargs={"pk": self.pk})
    
class TNAnmerkung(models.Model):
    teilnehmer = models.ForeignKey(Teilnehmer, verbose_name="Teilnehmer", on_delete=models.CASCADE)
    ausbilder = models.ForeignKey(Ausbilder, verbose_name="Ausbilder", on_delete=models.CASCADE)
    date = models.DateTimeField("Datum", auto_now=False, auto_now_add=True)
    comment = models.TextField("Anmerkung")

    class Meta:
        verbose_name = "TNAnmerkung"
        verbose_name_plural = "TNAnmerkungen"
        ordering = ['-date']

    def __str__(self):
        return f"{self.teilnehmer} - ({self.date}/{self.ausbilder.short}) {self.comment} " 

    def get_absolute_url(self):
        return reverse("TNAnmerkungen_detail", kwargs={"pk": self.pk})

class LaptopTN(models.Model):
    number = models.CharField("Laptop Nummmer", max_length=50)
    tn = models.ForeignKey(Teilnehmer, verbose_name="Teilnehmer", on_delete=models.CASCADE)
    ausgabe = models.DateField("Ausgabe", auto_now=False, auto_now_add=False, null=True, blank=True)
    ausgabevon = models.ForeignKey(Ausbilder, related_name = "Ausbilderausg", verbose_name="Ausgegeben von", on_delete=models.CASCADE, null=True, blank=True)
    ruecknahme = models.DateField("Rücknahme", auto_now=False, auto_now_add=False, null=True, blank=True)
    ruecknahmevon = models.ForeignKey(Ausbilder, related_name = "Ausbilderrueck" ,verbose_name="zurückgenommen von", on_delete=models.CASCADE, null=True, blank=True)
    anmerkung = models.TextField("Anmerkung", null=True, blank=True)

    class Meta:
            verbose_name = "Teilnehmer Laptop"
            verbose_name_plural = "Teilnehmer Laptops"
            ordering = ['tn', '-ausgabe']

    def __str__(self):
        return f"{self.number} - {self.tn} ({self.ausgabe} - {self.ruecknahme})"

    def get_absolute_url(self):
        return reverse("LaptopTN_detail", kwargs={"pk": self.pk})

stammdaten/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def start(request):
    return HttpResponse("Startseite")

def user_login(request):
    name = request.POST['name']
    password = request.POST['password']
    cont = request.POST['cont']
    user = authenticate(request, username=name, password=password)
    if user is not None:
        login(request, user)
    if ":" in cont:                     # url auflösen
        cont = reverse(cont)
    return redirect(cont)
    # Redirect to a success page.

def user_logout(request):
    cont = request.POST['cont']
    logout(request)
    return redirect(cont)

stammdaten/templates/stammdaten/base.html
{% load static %}

<!doctype html>
<html lang="de">

<head>
    <title>{% block title %}Ausbildungsplan Entwurf{% endblock title %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS v5.2.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"> 
    <script>let benutzer = '{{request.user}}'</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.3/moment.min.js">
    </script>
    <script src="https://code.jquery.com/jquery-4.0.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <header class="d-print-none mb-2">
        <!-- place navbar here -->
        <div class="container-fluid bg-dark-subtle fixed-top shadow opacity-75">
            <div class="row g-2 border bg-dark-subtle">
                <nav class="navbar navbar-expand-lg col">
                    <div class="container-fluid">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item ">
                                    <a class="nav-link text-danger" aria-current="page" href="/admin" target="__blank">Admin</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="{% url 'ausbildungsplan:start' %}">Ausbildungsplan</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Rahmenlehrplan</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'anw:start' %}">Anwesenheit</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <div class="col row">
                    {% block zusatzmenue %}{% endblock zusatzmenue %}    
                </div> 
                {% comment %} Anmeldebereich {% endcomment %}
                <div class="col">
                    {% if user.is_authenticated %}
                    <form action="{% url 'stammdaten:logout' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{cont}}" name="cont">
                        <button class="float-end btn btn-outline-secondary">Abmelden</button>
                        <p class="float-end">{{user.username}}</p>
                    </form>
                    {% else %}
                    <form action="{% url 'stammdaten:login' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{cont}}" name="cont">
                        <button class="float-end">Anmelden</button>
                        <input class="float-end" type="password" placeholder="Passwort" name="password" tabindex="1">
                        <input class="float-end" type="text" placeholder="Benutzername" name="name" tabindex="2">
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
    <main>
        <div class="container" style="margin-top: 5em;">
            {% block content %}
            {% endblock content %}
        </div>
        <div class="container-fluid" style="margin-top: 5em;">
            {% block content_fluid %}
            {% endblock content_fluid %}
        </div>
    </main>
    <footer>
        <!-- place footer here -->
    </footer>
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    {% block js %}
    {% endblock js %}
</body>

</html>